version: '3.8'

services:
  payment-hub:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: payment-hub
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:paymenthubdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - ./src:/app/src