global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'payment-hub'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'payment-hub-1:8080'
          - 'payment-hub-2:8080'
          - 'payment-hub-3:8080'

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'payment-hub-1:8080'
          - 'payment-hub-2:8080'
          - 'payment-hub-3:8080'